### ISSUE TITLE
[BUG] - 2021 Results Not Showing on Our Site

### ISSUE THREAD

**Issue by skateandlacroix** [nmelhado/league-page#107]
**Describe the bug**
Our season is over but we still see the 2020 Champ information listed on the front page of the website. Also, on the Trophy Room page, the most recent results are from 2020. We are not seeing 2021 results on these two pages.

**Your League ID**
786076885619908608

**To Reproduce**
1. Go to https://league-page-ecigpe9i7-skateandlacroix.vercel.app
2. You'll see the 2020 Champ listed
3. Click on League Info, then Trophy Room and you'll see 2020 results as the most recent.

**Expected behavior**
I expected to see the 2021 results on the site by now. Our season is now over and we've over to the 2021 postseason.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Additional context**

**Comment by nmelhado** [comment]
Sleeper unfortunately assigns a new league ID each season, so once you renew you should get a new league ID. Update your page with the new league ID and all of your information should update.
