### ISSUE TITLE
[BUG] FAAB Waivers not working

### ISSUE THREAD

**Issue by rebell218** [nmelhado/league-page#11]
**Describe the bug**
My league is using FAAB for Waivers. I noticed that on Transactions a Player who got multiple bids, is shown multiple times.

**Your League ID**
650025991288205312

**To Reproduce**
1. Go to https://rmdotasource.vercel.app/transactions?show=both&query=&page=1 and look for Waiverpickups 

**Expected behavior**
People who didnt got the Player shouldnt pop up here

**Screenshots**
![grafik](https://user-images.githubusercontent.com/88341831/128087950-5b2be2a5-a1c3-4572-b6c8-bcae84ce9683.png)

**Comment by nmelhado** [comment]
Found the rc. I didn't realize that the sleeper API includes failed bid requests in its transaction API. I'm including the fix (to filter failed bids out) in a refactor PR going up tonight

Example:
```
{
    "waiver_budget":[],
    "type":"waiver",
    "transaction_id":"725808153878417408",
    "status_updated":1627477484756,
    "status":"failed",
    "settings":{
        "seq":3,
        "priority":1
    },
    "roster_ids":[11],
    "metadata":{
        "notes":"This player was claimed by another owner."
    },
    "leg":1,
    "drops":null,
    "draft_picks":[],
    "creator":"386602135267266560",
    "created":1627408658049,
    "consenter_ids":[11],
    "adds":{"928":11}
}
```

**Comment by nmelhado** [comment]
Fixed by pr https://github.com/nmelhado/league-page/pull/14
