### ISSUE TITLE
[ENHANCEMENT] Commissioner label or designation in managers tab ???

### ISSUE THREAD

**Issue by mnewk41** [nmelhado/league-page#125]
Would it be possible to add some sort of designation or label for the commissioner in the league. Maybe add it under the line that says "manager of ..." or even make it a bubble on the bottom like the vets, fav player, and rival. That way those visiting the site that may not be in the league knows who the commish is.

**Comment by nmelhado** [comment]
Sorry for the slow response here. Yes, this is definitely possible. I'll try to add a badge in a couple places. Should be able to get this done before the beginning of the season

**Comment by mnewk41** [comment]
Is there an update on this feature?

@nmelhado

**Comment by nmelhado** [comment]
Sorry for the delay, due to security updates, I needed to do a fairly substantial re-write to get things working again. I'll be looking to get this done in the next couple weeks. It's next up on the todo list

**Comment by nmelhado** [comment]
Going to try to add this to the upcoming update... within the next couple weeks. Sorry for the delay, low bandwidth recently for implementing changes.
