### ISSUE TITLE
[BUG] League Page not responding

### ISSUE THREAD

**Issue by mnewk41** [nmelhado/league-page#132]
I had to delete my old page and re-fork this one and add my info back to it cuz it would not let me merge the updates, however upon doing this my page is now unresponsive. Nothing loads and the clickables aren't working

**Comment by nmelhado** [comment]
Can you provide your league ID, as well as your league url? I'll try to look into it this week

**Comment by mnewk41** [comment]
https://317-812-league-page-mztswatjh-mnewk41.vercel.app/


317-812-League-Page

**Comment by mnewk41** [comment]
Update: I tried it on my phone and it is working there. I will try again on desktop and see if it works

**Comment by nmelhado** [comment]
It might have been a caching issue where the old info was still cached on your page. That's the only explanation I can think of. I'm a little overworked at the moment, so I haven't had a chance to test this locally. But it's working for me as of now.

**Comment by nmelhado** [comment]
I can't reproduce this locally and think it was probably due to caching. If you still think there's a bug, reopen it and let me know.
