### ISSUE TITLE
[ENHANCEMENT] Adding Telegram logo to "Preferred contact method" list

### ISSUE THREAD

**Issue by mscipio** [nmelhado/league-page#135]
Hi, 
I have added a small `Telegram.png` logo to my custom fork of this repo so that managers can select that option in their "preferred method" to be contacted. That's because most of our league discussion happens there. I have also updated the `TRAINING_WHEELS.md` file and the `leagueInfo,js` to reflect the ... new functionality.

I wanted to open a pull request to merge that to your main repo, but I am not sure what I am supposed to do, or if I am even allowed to. Of course, if you don't care about this feel free to close this issue.

Thanks!

**Comment by nmelhado** [comment]
You are definitely allowed to open a PR! Open one up with the changes and I'll check it out as soon as I can. I appreciate the help.

**Comment by nmelhado** [comment]
You should be able to open a pr by making a branch in your forked repo and trying to merge it back into the parent master branch. If that doesn't work, I'll use an alternate account to document the steps.

**Comment by nmelhado** [comment]
Closing for now. If you're still having trouble, open a topic in the discussions page so that we can try to debug further!
