### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chor5e** [nmelhado/league-page#138]
**Describe the bug**
Tables added within the Contentful content editor do not show up in the blog post once published to team page.

**Your League ID**
784407599985639424

**To Reproduce**
1. Go to Contentful > Content
2. Create new content with content type = Blog Post
3. Add tabular content using the rich text editor 2x2 table button and publish content
4. See unexpected display on Vercel team page

**Expected behavior**
Blog post on page should display the table as it's created in the Contentful content editor

**Screenshots**
![Capture1](https://user-images.githubusercontent.com/106204969/181546562-65fd33ae-693b-412d-954c-4385f15d214a.PNG)
![Capture2](https://user-images.githubusercontent.com/106204969/181546592-64b2b87d-ffdd-4b8c-8991-8cb55b201258.PNG)

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Browser= Chrome

**Comment by nmelhado** [comment]
I'm going to track this in https://github.com/nmelhado/league-page/issues/140 instead, as it has more issues highlighted. I will try to get this finished before the start of the season.
