### ISSUE TITLE
[ENHANCEMENT] Add images/tables/elements to blog posts

### ISSUE THREAD

**Issue by SnekSnek35** [nmelhado/league-page#140]
**Is your feature request related to a problem? Please describe.**
Hi, thank you so much for this resource first of all. When I add tables/images to my blog posts in Contentful, they do not appear on the site page when I publish the blog.

**Describe the solution you'd like**
Add the capability for blog posts to contain tables/images/graphs if possible

**Describe alternatives you've considered**
I originally tried a table, then tried to embed a screenshot and that didn't work either.

**League ID**
860920784586158080

**Additional context**
My goal for blogs is to add a series of stats posts with graphs and tables. This was just a simple test of using tables with a 2x11 draft order table with headers.

I'm not super proficient with coding, but I did find in Contentful's library that they have a rich text package to help enable these types of objects in [blog posts](https://github.com/contentful/rich-text). I'm just not really sure how to implement.

**Comment by chor5e** [comment]
FYI - related to bug #138

**Comment by nmelhado** [comment]
The handling of each element from Contentful is done manually, and I completely missed these. I'll try to get this finished before the start of the season

**Comment by nmelhado** [comment]
tables and images should now be loading correctly, it will require a new API key though. Please look at the training wheels guide for the directions
