### ISSUE TITLE
[BUG] Dev environment not working

### ISSUE THREAD

**Issue by JGH85** [nmelhado/league-page#149]
**Describe the bug**
I forked the repo and successfully deployed the customized league website with my league. I would also like to try developing some salary features, but when I attempt to run the app for dev purposes I get errors referring to missing source files in the folder /node_modules/@material/ (see screenshots below - there are a lot more of these missing files. the list goes on for a few pages).
The webpage appears as simply a blank screen in the browser and gives a console error in the browser as well (screenshot 2). It's very possible that I messed up something in the setup process but I'm stuck figuring out what that could be. 

Any help would be appreciated!

**Your League ID**
859990766557179904

**To Reproduce**
I'm not sure you'll be able to reproduce this in another environment since the issue is what's it's doing on my local pc. However, here are the steps I did. 
1. Fork and clone repo to local machine. 
2. npm install
3. npm run dev --

**Screenshots**
![image](https://user-images.githubusercontent.com/19660161/188238295-7352466d-48b6-46e2-9919-9c9e78a00489.png)
![image](https://user-images.githubusercontent.com/19660161/188238393-18ebb918-ec6f-4386-884b-ceafcd8cd76c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Chrome 105

**Additional context**
The only changes I made previously were to comment out most of the text on the league rules page but I don't see how that could have broken anything.

**Comment by nmelhado** [comment]
I'm working on a PR to fix this. Vercel needed an update for security purposes but that broke local dev. The fix is unfortunately quite extensive as many packages need to be upgraded and they come with quite a few substantial breaking changes. Hoping to get it up as soon as possible

**Comment by JGH85** [comment]
OK no hurry. I'm glad to hear it wasn't just me. I code a decent amount but hadn't played with svelte before so I thought I must have messed something up.

**Comment by nmelhado** [comment]
This should be fixed now
