### ISSUE TITLE
[ENHANCEMENT] Roster Page record bubble reset?

### ISSUE THREAD

**Issue by mnewk41** [nmelhado/league-page#151]
Hi I was just wanting  ask a general question. On the roster tab where it shows the team name and underneath has the green and red bubbles signifying wins and losses, will those reset once week 1 is complete so we can see them fill in color week by week?

thank you

**Comment by nmelhado** [comment]
Yes they will! The data comes from Sleeper and for some reason instead of resetting to no wins and losses durning the off-season, it keeps the previous season's win record until after week 1
