### ISSUE TITLE
[BUG] Standings

### ISSUE THREAD

**Issue by mnewk41** [nmelhado/league-page#153]
**Describe the bug**
Issue with the standings where it outputs "Preseason, No Standings Yet" following week 1 of fantasy season.

**To Reproduce**
1. Go to 'Standings'
2. See error

**Expected behavior**
Page loads and displays no standings

**Screenshots**
![image](https://user-images.githubusercontent.com/105653530/189969595-334f4f6e-6686-4a8b-a17b-52c70f77c00e.png)

**Comment by nmelhado** [comment]
Standings should be displaying now. It waits until Sleeper has officially declared week 1 over (usually towards the end of day Tuesday) to update standings.

If yours stop isn't working, feel free to re-open!
