### ISSUE TITLE
[BUG] Teams not listed by correct owner on the Manager page

### ISSUE THREAD

**Issue by mnewk41** [nmelhado/league-page#154]
**Describe the bug**
Team names are not by the correct manager names. 

**Your League ID**
League ID: 317-812-League-Page

**To Reproduce**
1. Go to 'managers'
2. Scroll down thru names and see if teams match up to managers

**Expected behavior**
Managers and their team names are not the same

**Screenshots**
![image](https://user-images.githubusercontent.com/105653530/189971355-6b666a60-2a14-4e47-ab6b-dd1e88989009.png)
Correct Teams and Managers
Mason-RTDB
Tyler-Suspended
Jared-Fantasy Football Team
Jake-Team Username
Tommy-Get Cook'd
JT-Lights Kamara Action
Andrew-Red Solo Kupps
AJ-Ajew
Chris-J-E-T-S
Levi-BigJohnson50

**Comment by nmelhado** [comment]
Could you post a screen shot of some of the manager configuration, and another of your power ranking chart?

**Comment by mnewk41** [comment]
it looks like the issue resolved itself. not sure what the issue was. I will close the issue. Thank you for your response
