### ISSUE TITLE
Fetching updates leads to overwriting own data

### ISSUE THREAD

**Issue by Justatix** [nmelhado/league-page#165]
Hi, I might probably be wrong here, but I have following problem:

I did forge the latest updates on my homepages yesterday via github repository (redcomleague.vercel.app), since it was showing the need for it directly on my homepage. Mainly I triggered the fetching update process, due to the fact that the future draft calculation process remained stuck at 20 % even after refreshing.
However, after the update, my data entered in my homepage and all my by laws were no longer available, and the "lorem ipsum" default text appeared again on the main page and your default by laws were shown. Is there a chance to somehow restore previous versions of it, in order to keep them even after the update?
Thanks for your reply.

**Comment by nmelhado** [comment]
Updating shouldn't overwrite your changes. However this was a massive overhaul do to some underlying changes. It's possible something went wrong during the update. If you look back at your old commits, you should be able to copy your work over.

This shouldn't happen in the future, as I don't expect the dependencies to make such massive changes going forward.

As for the percentage loading, that's not a loading bar 😬. It's an accuracy bar. As the season progresses, the draft order becomes more certain and the bar will increase. Sorry if that was misleading!

**Comment by Justatix** [comment]
Thanks for your reply. Tbh I am pretty a noob wrt Github and its functionalities... by looking at my commits I am only able to see yours rather than mines :-/ 

<img width="1677" alt="Bildschirmfoto 2022-09-26 um 20 04 10" src="https://user-images.githubusercontent.com/95846607/192348414-232ff13f-a336-417c-bcb8-c3bfe1756d5b.png">

Am I searching at the wrong place? I know that my updates were made at the beginning of September (5th or 6th) but I can't find them any longer...

and if I try to open my vercel homepage, i now get an error message.

<img width="679" alt="Bildschirmfoto 2022-09-26 um 20 03 24" src="https://user-images.githubusercontent.com/95846607/192348265-269e8882-3bc0-463b-ab4a-708200649dd6.png">

Would you suggest to create a new page rather than trying waste too much time elsewhere?

**Comment by nmelhado** [comment]
That's where they should show up. I'm not sure how/why that happened. Updating should never remove your existing work. Without being able to retrieve your previous commits, you'll unfortunately have to start over. Sorry for the inconvenience

**Comment by Justatix** [comment]
no issues, will restart from scratch. Would you know if I could still re use the homepage link from vercel or if i have to consider a new one as well there? basically can I map the new page I'll create from Github to the existing placeholder/homepage from Vercel?

**Comment by Justatix** [comment]
never mind, I tried it out and found how to map it accrodingly. Everything seems to be fine now, thanks again for your support
