### ISSUE TITLE
Constitution page no longer retrievable

### ISSUE THREAD

**Issue by Justatix** [nmelhado/league-page#166]
Hi,

in your training wheels you state that league constitution page is to be found under  /src/routes/constitution/index.svelte 
however if I verify my repository, I cannot find the editable page but I see only this overview:

<img width="824" alt="Bildschirmfoto 2022-09-27 um 21 03 10" src="https://user-images.githubusercontent.com/95846607/192613500-46abfa46-b4d7-45bc-bc98-06192c9f70b7.png">

Would you know if this page was moved to another folder?

Thanks for your feedback
Fulvio

**Comment by nmelhado** [comment]
Yes, due to a change in svelte kit, I had to move things around to get it working. It's now +page.svelte in that same directory (instead of index.svelte). I'll update the docs in the near future to avoid confusion. Thanks for bringing this to my attention!

**Comment by Justatix** [comment]
appreciate your fast reply.
Can i assume that i can overwrite the text like in the previous settings (with html code) without having to consider specific points?

**Comment by nmelhado** [comment]
Yes, other than the file name it should be the exact same.

**Comment by nmelhado** [comment]
If anyone would like to update the documentation in the README and TRAINING_WHEELS, it would be much appreciated!

If not, I'll do it in the next PR.
