### ISSUE TITLE
[ENHANCEMENT]

### ISSUE THREAD

**Issue by Iconstant100** [nmelhado/league-page#175]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't create more than one fork

**Describe the solution you'd like**
I want to be able to create more than one fork so I can host multiple leagues.

**Describe alternatives you've considered**
I am the lead commissioner on a 24-team league that is split between two 12-team leagues. I have considered having the commissioner of the other league create a github account, but I know this coding process will be over his head. I would like to create both so that participants in both leagues can see the standings in the other league. All 24 teams are friends/colleagues.

**League ID**
My league ID (which is set up thanks to nmelhado) is: 863634329077706752
The league I would like to create a website for is: 863634326343004160

**Additional context**
I just want to create two forks of this website with a single GitHub account. Also, thank you for making this a possibility!

**Comment by nmelhado** [comment]
I would fork it and leave an untouched master that you sync with the main page for updates. Then create multiple branches for the different leagues. When there's updates, sync the updates to master and then to the league branches. Then in vercel make different websites based on the branch.
