### ISSUE TITLE
[ENHANCEMENT] extend possibilities for manager infos

### ISSUE THREAD

**Issue by HansPeterOrding** [nmelhado/league-page#18]
**Is your feature request related to a problem? Please describe.**
I have managers in my league that want to leave out answers or submitted answers that i can't enter:
* fantasyStart, favoriteTeam, mode, favoritePlayer, valuePosition, rookieOrVets should be "nullable", i.e. the possibility of displaying a question mark or something similar should be possible
* favoritePlayer currently must be listed in sleeper. Is it possible to extend this to another source (like nflfastr or similar) to enable older players like John Lynch?

**Describe the solution you'd like**
* Introduce null values for the mentioned variables. 
* If null values are set in managers.js, display a questionmark in the templates
* Use a source for players that lists older players

**League ID**
640240064185606144

**Comment by nmelhado** [comment]
For the first half, that's no problem. Would you prefer a ? or to just omit that element altogether?

For the second part, if you know of a free API that can return player images, I can look into adding that for more flexibility.

**Comment by nmelhado** [comment]
Thank you! Much appreciated. Also thank you for submitting the bugs and enhancement suggestions. The hardest part about building this is accommodating for all of the different league permutations, so I greatly appreciate the timely feedback you've been giving

**Comment by nmelhado** [comment]
I'm closing this for now unless there are other specific enhancements that are needed. Hope this worked well for you in the '21 season!
