### ISSUE TITLE
Transaction History Between Managers

### ISSUE THREAD

**Issue by namkurd** [nmelhado/league-page#181]
Would be cool to see a relational spiderweb-type graphic based on the trades made between managers to see who has had the strongest relationship historically. 

Would be especially cool if it was weighted based on the player value in the trade (based on some sort of trade analyzer from the week the trade was made)

Thanks for the all the work that went into this and making it public!

**Comment by nmelhado** [comment]
It would be really fun to make a new page where you can select two managers and see their entire history! Matchups, trades, and even head to head comparison of their records and rankings. I'm short on bandwidth, but I'll definitely put this on the roadmap.

Great idea!

**Comment by nmelhado** [comment]
I'm going to lump this in with https://github.com/nmelhado/league-page/issues/160 and create a rivalry page that keeps track of matchups/transactions between two managers
