### ISSUE TITLE
[BUG] Deployment in Vercel returns failure

### ISSUE THREAD

**Issue by Justatix** [nmelhado/league-page#196]
**Describe the bug**
After having amended some text in constitution page, the automatic deployment to Vercel failed

**Your League ID**
918152922595315712

**To Reproduce**
Edit text in constitution page

**Expected behavior**
Successful deplyoment in Vercel

**Screenshots**
<img width="1251" alt="Bildschirm­foto 2023-03-26 um 15 13 19" src="https://user-images.githubusercontent.com/95846607/227778157-c9d30345-04fd-416c-ac91-38498ea9a9c9.png">

**Desktop (please complete the following information):**
MacOS 13.2.1
. 22]

**Comment by nmelhado** [comment]
On line 182, you have a </ul> but no <ul> that it's closing. You need to delete the </ul> or add a <ul>

**Comment by Justatix** [comment]
thanks for your feedback. I used another html converter in order to have constituion details being published correctly.
