### ISSUE TITLE
[BUG] Rosters never load

### ISSUE THREAD

**Issue by iamjacksdistraction** [nmelhado/league-page#199]
**Describe the bug**
Stuck "Retrieving roster data" no matter how many times I try and configure this from scratch or how long I wait for it to load. Using the guide here: https://github.com/nmelhado/league-page/blob/master/TRAINING_WHEELS.md 

**Your League ID**
918170866318491648

**To Reproduce**
1. Follow the training wheels guide
2. Set league name and League ID
3. Deploy League Page via Vercel
4. Attempt to load rosters page on Vercel site (e.g. https://league-page-ywlq.vercel.app/rosters )

**Expected behavior**
Rosters should load

**Screenshots**
![image](https://user-images.githubusercontent.com/121634775/231861607-470fd0ac-d39d-4bcd-83e3-ee4927dc41d6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 111.0.5563.147 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by nmelhado** [comment]
Should be fixed. @sillebt this should also fix your issue
