### ISSUE TITLE
[BUG] Rivalry screen stuck on loading screen

### ISSUE THREAD

**Issue by BravesVolsUU** [nmelhado/league-page#204]
**Describe the bug**

When I try to check out the rivalry on the webpage (https://draftdaydynasty.vercel.app/rivalry), I'm able to select two managers to compare, but the screen is stuck on "analyzing rivalry" and just continues spinning.

**Your League ID**

917928509921222656

**To Reproduce**
1. Go to League Info
2. Click on 'Rivalry'
3. Pick any two managers

**Screenshots**

![Screenshot 2023-04-30 012712](https://user-images.githubusercontent.com/88356004/235339104-c4433e3a-a897-447c-8686-a297af7958bd.png)

 - Occurring on multiple platforms. Mostly trying to access on Google Chrome (112.0.5615.137 for Windows & Mac)
 - Also trying on iOS 16.4.1 on iPhone 13 Pro Max.

**Comment by nmelhado** [comment]
@BravesVolsUU should be fixed now
