### ISSUE TITLE
[ENHANCEMENT] IDP Positions

### ISSUE THREAD

**Issue by ulle1803** [nmelhado/league-page#22]
Id like to have pictures for the following IDP positions: CB, SS, FS, DE, DL, LB

**Comment by nmelhado** [comment]
Got caught up adding brackets to the matchup page, will add this and the dynasty option from https://github.com/nmelhado/league-page/issues/21 tomorrow!

**Comment by nmelhado** [comment]
Filled in PR https://github.com/nmelhado/league-page/pull/25
