### ISSUE TITLE
[BUG] Resources page broken after last update 

### ISSUE THREAD

**Issue by Zuid81** [nmelhado/league-page#230]
Hi,

first of all thank you for all the effort and work going into this. Having said that, it seems like the last update broke the resources page. Since it’s also happening on your own league page it’s an issue in general.

**Comment by nmelhado** [comment]
There was a security issue with the previous xml parser. I had to update it in the last update. I think that may have unintentionally broken the news API. I'll try to look into it this week. Thanks for reporting!
