### ISSUE TITLE
[BUG] Drafts - Not all previous drafts or future draft are showing

### ISSUE THREAD

**Issue by dawghouse73** [nmelhado/league-page#240]
**Describe the bug**
Related to discussion #223 

Currently, by default, our Drafts page shows two items:
- Next Season Draft Board (2024)
- Rookie Draft (held in May 2023)

What's missing:
- Our Initial Veterans Only Start Up draft from February 2023
- The Draft Board for 2025
- We allow the trading of picks for the next rookie draft and the following rookie draft. It would be nice to see the board and the picks owned by each manager for both next year and the year after. What I'm hoping to be able to see is the following:

What I'm hoping we can have show is:
- Current Year + 1 Draft Board (ex. 2024)
- Current Year + 2 Draft Board (ex. 2025)
- Most Recent Rookie Draft for each year (ex. 2023)
- Inaugural Draft (ex. for us it was earlier in 2023)

I know the API can pull this information (I've pulled it into Google sheets already), I think it just needs a check to see if there were more than one draft in a year (we split our start up and rookie drafts in year 1).
And as a bonus, maybe a configuration setting to allow us to pull in either 1 or 2 or 3 future years draft boards (Sleeper currently allows draft pick trading for up to 3 future years (it cannot restrict to more or to less - it's always three). 
Our league allows for picks to be traded for 2 future years, so a setting in leagueinfo.js or somewhere to allow us to set 1, 2, or 3 future years which would then drive how many future boards are showing. 

This issue is a combination of a a bug (missing 2025 draft, missing Inaugural Draft) and an enhancement (configuration to allow for 1-2-3 future draft boards to be shown via leagueinfo.js). 

**Your League ID**
League ID: 922637695908737024
Site: shulacesoutdan.vercel.app

**To Reproduce**
1. Go the League Info menu
2. Click on Drafts

**Expected behavior**
When comparing to the Legends  League page, they show all drafts (I believe), including their inaugural draft.
All previous Rookie Drafts are showing back to 2020.
The inaugural draft in 2019 is showing. 
Next year's 2024 draft board is showing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome (15.0.5790.110); 
 - Browser: Opera (99.0.4788.88)
 - Browser: Firefox (115.0.2)
 - Browser: Edge (115.0.1901.188)

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS16.1.1
 - Browser: Chrome (115.0.5790.130)
 - Browser: Safari (v16)

**Additional context**
All existing draft data is showing accurately.

**Comment by nmelhado** [comment]
@dawghouse73 the bug portion of this is fixed! Feel free to open up a new ticket requesting additional future draft boards

**Comment by dawghouse73** [comment]
Thanks – created a new enhancement request and referenced #240 in the request.


Thanks for everything.

 

House
