### ISSUE TITLE
[BUG] 404 Error on Manager Profile Pages and Rivalry Page

### ISSUE THREAD

**Issue by ittwa** [nmelhado/league-page#244]
**Describe the bug**
The 404 page ("Hut, Hut, Blue 404!") shows on the [Rivalry page](https://www.ittwa.com/rivalry) and on any [individual manager page](https://www.ittwa.com/manager?manager=0).

_edit: this also shows on the [Records page](https://www.ittwa.com/records) as well._

**Your League ID**
918205115247595520

**To Reproduce**
1. Go to the [`Managers` page](https://www.ittwa.com/managers)
2. Click on any Manager
3. See error

OR

1. Go to the [`Rivalry` page](https://www.ittwa.com/rivalry)
2. See error

**Expected behavior**
I expect to see the pages like you have on your site ([Manager profile](https://www.legendsleagueff.com/manager?manager=1), [Rivalry](https://www.legendsleagueff.com/rivalry))

**Screenshots**
<img width="1439" alt="image" src="https://github.com/nmelhado/league-page/assets/123038339/9a5eef55-c7fb-4677-bfbd-feeaf3d6438c">

<img width="1438" alt="image" src="https://github.com/nmelhado/league-page/assets/123038339/20e08234-0b4d-4cb5-baaa-d1e8b76e4fa2">

**Desktop:**
 - OS: macOS Monterey v 12.6
 - Browser: Brave
 - Version: 1.56.20 Chromium version 115.0.5790.171.
 
 _edit: I've also confirmed this is happening in Chrome as well._

**Smartphone:**
 - Device: iPhone 13
 - OS: iOS 16.6
 - Browser: Brave
 - Version: 1.52.1 (23.7.11.14)

**Additional context**
@nmelhado I'm sure this could just be an error/oversight on my part as setting up a website is all relatively foreign to me. I followed your instructions and everything is working on my [site](https://www.ittwa.com), except for the manager profile pages and rivalry pages. Here is my [repo](https://github.com/ittwa/league-page) if it helps. Thanks!

**Comment by TannerHopkins** [comment]
+1
Similar issue here, but weirdly only happening with one of my league sites - the only differences are the `leagueInfo.js` and `badge.png` files - otherwise all of the rest of the repository is exactly the same (confirmed this).

**Comment by TannerHopkins** [comment]
@ittwa - out of curiosity, has your league ever been reset?

**Comment by ittwa** [comment]
Thanks for the additional context, @TannerHopkins. I don't believe my league has ever been reset, but it could have been like ~4 years ago when I was initially migrating from ESPN.

@nmelhado any chance you can look into this? I'm hoping to share this site with my league prior to the start of the regular season.

**Comment by TannerHopkins** [comment]
Not the most technical here (at least with websites), but I used the chrome "inspect" feature and checked the console and found this exact error for both of my pages:
<img width="537" alt="image" src="https://github.com/nmelhado/league-page/assets/32333995/cea0d41c-7fd0-45d7-8921-1c1a10cba907">

Feel like this should help a little with the debugging.

If you want to look for yourself, here is my (failing) website: https://grandexchange.vercel.app/

**Comment by TannerHopkins** [comment]
I had another theory on something different about my league - we've had a couple of waiver force adds to teams, which shows up as a different type of transaction (`"type":"commissioner"`). That being said, it looks like this repo does not currently track `"type":"free_agent"` transactions either, so I'm doubtful that a different type of transaction than the current 2 that are being tracked (`waiver` and `trade`) would break anything - unless it doesn't like that the `commissioner` transactions are created by one user but impact another user's roster?
Just thinking out loud here 🤷🏻

**Comment by nmelhado** [comment]
Sorry for the delay all. I've been super busy and haven't had a chance to debug at all. Finally got around to it this morning. he bug was happening because somehow in both of your leagues there were some matchups with only 1 team. I've added a simple fix which should resolve your issues!

**Comment by nmelhado** [comment]
The bug portion of this is fixed! Feel free to open up a new ticket requesting additional future draft boards

**Comment by nmelhado** [comment]
@TannerHopkins and @ittwa this is now fixed. If you're still seeing any issues after you update, please let me know!

**Comment by ittwa** [comment]
Thanks, @nmelhado! Looks great!

**Comment by TannerHopkins** [comment]
Thanks so much @nmelhado ! No worries on the delay at all, appreciate all that you've done for creating this in the first place. Excited to see how my league likes it!

**Comment by sethtobrien** [comment]
Hello! I'm having a similar issue on this page. 

Here is my code:
<img width="692" alt="image" src="https://github.com/nmelhado/league-page/assets/140202779/a464041b-b1ef-44f6-8fa3-f7e308d49f44">

Here is my league page: 
https://therealv3-sethtobrien.vercel.app/managers

Any help is greatly appreciated!
