### ISSUE TITLE
[ENHANCEMENT] Discord as additional Contact Source

### ISSUE THREAD

**Issue by rebell218** [nmelhado/league-page#26]
My Leaguemates are communicating mostly over Discord. I uploaded a Discord.png to /static/ and tried out if its working that simple by just typing "Discord" in the /src/routes/managers/managers.rs. Working like a charm, so I suggest you could also update your template (I'm new to github and don't know how everything works here exactly) 

You can use this .png
![Discord](https://user-images.githubusercontent.com/88341831/128604094-2a3f3910-9782-42b1-b22c-7f1e2893d3ef.png)

![grafik](https://user-images.githubusercontent.com/88341831/128604112-a48ac0a3-ab56-4ebe-9b0f-d92c4d0848a0.png)
![grafik](https://user-images.githubusercontent.com/88341831/128604148-aeb1dfdc-c68b-4b4e-9247-33822369b4af.png)

**Comment by nmelhado** [comment]
Thank you very much! I'm releasing a new update later today and will include this. Thank you for the improvement and providing the file!

**Comment by nmelhado** [comment]
Discord logo added in https://github.com/nmelhado/league-page/commit/e9b37b9907492a1b421cd095d820e3ce3bc8e502
