### ISSUE TITLE
[BUG] Can't post comments on blog

### ISSUE THREAD

**Issue by jalbert4** [nmelhado/league-page#268]
**Describe the bug**
When trying to post a comment, receive 'Unauthorized user' message when entering Sleeper Username. 

**Your League ID**
916476233674907648

**To Reproduce**
1. Go to full blog post
2. Click on LEAVE A COMMENT
3. Type anything into the comment section
4. Type your Sleeper Username
5. Click SUBMIT COMMENT
6. See Error

**Expected behavior**
I expect the comment to post to the blog

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome & Edge
 - Version: 116.0.5845.111

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 13
 - Browser: Chrome
 - Version: 116.0.5845.111

**Additional context**
I can get the comment to post if I use the full name of the manager as opposed to the Sleeper Username but it does not pull the profile picture or link to the manager's website profile. However, if I initiate the blog comment from Contentful, it will post correctly if I type the Sleeper Username when initiating from Contentful. Also, if I create a comment on the site using the full name, I can then go to Contentful and edit the author field under the comment to the Sleeper Username and it will work correctly.

**Comment by nmelhado** [comment]
My bad, this slipped through the cracks. I'll push up a fix shortly
