### ISSUE TITLE
[BUG] Draft Page

### ISSUE THREAD

**Issue by mnewk41** [nmelhado/league-page#279]
Nick, I recently lost some of my pages during the sync to update my website. You helped me in the past on reddit but chats from pre-2023 were wiped. Can you tell me where i can go to find the draft id page that translates the draft results onto the website

**Comment by nmelhado** [comment]
Hey sorry, catching up on past issues. Do you still need help with this?

**Comment by mnewk41** [comment]
i believe i figured it out. thanks for checking in!
