### ISSUE TITLE
[BUG] Playoffs under Matchup does not work.

### ISSUE THREAD

**Issue by alexszura1** [nmelhado/league-page#289]
**Describe the bug**
When clicking 'playoffs' under 'matchup', the site appears to freeze/nothing loads, so you have to go back to the home page and click refresh to get out of this.

**Desktop (please complete the following information):**
Windows, Microsoft Edge

**Additional context**

**Comment by JDIacobbo** [comment]
I can confirm I am having the same issue running Firefox.

**Comment by HashSlingSlash** [comment]
To fix this go to universalFunctions.js in utils/helperFunctions and replace the getAvatarFromTeamMangers function with the following code which includes error handling.

`export const getAvatarFromTeamManagers = (teamManagers, rosterID, year) => {
    if(!year || year > teamManagers.currentSeason) {
        year = teamManagers.currentSeason;
    }
    const yearManagers = teamManagers.teamManagersMap[year];
    if (!yearManagers) {
        // Handle the case where the year is not in teamManagersMap
        return null; // or a default value
    }
    const roster = yearManagers[rosterID];
    if (!roster || !roster.team) {
        // Handle the case where rosterID is not found or team is undefined
        return null; // or a default value
    }
    return roster.team.avatar;
}`

**Comment by JDIacobbo** [comment]
> To fix this go to universalFunctions.js in utils/helperFunctions and replace the getAvatarFromTeamMangers function with the following code which includes error handling.
> 
> `export const getAvatarFromTeamManagers = (teamManagers, rosterID, year) => { if(!year || year > teamManagers.currentSeason) { year = teamManagers.currentSeason; } const yearManagers = teamManagers.teamManagersMap[year]; if (!yearManagers) { // Handle the case where the year is not in teamManagersMap return null; // or a default value } const roster = yearManagers[rosterID]; if (!roster || !roster.team) { // Handle the case where rosterID is not found or team is undefined return null; // or a default value } return roster.team.avatar; }`

I don't think your code block pasted correctly. I tired to reformat it but I'm not super familiar with JS syntax. Does this look correct?

`export const getAvatarFromTeamManagers = (teamManagers, rosterID, year) => { 
	if(!year || year > teamManagers.currentSeason) { 
		year = teamManagers.currentSeason; 
	} 
	const yearManagers = teamManagers.teamManagersMap[year]; 
		if (!yearManagers) { // Handle the case where the year is not in teamManagersMap 
			return null; // or a default value 
		} 
	const roster = yearManagers[rosterID]; 
		if (!roster || !roster.team) { // Handle the case where rosterID is not found or team is undefined 
			return null; // or a default value 
		} 
	return roster.team.avatar; 
}`

**Comment by JDIacobbo** [comment]
> To fix this go to universalFunctions.js in utils/helperFunctions and replace the getAvatarFromTeamMangers function with the following code which includes error handling.
> 
> `export const getAvatarFromTeamManagers = (teamManagers, rosterID, year) => { if(!year || year > teamManagers.currentSeason) { year = teamManagers.currentSeason; } const yearManagers = teamManagers.teamManagersMap[year]; if (!yearManagers) { // Handle the case where the year is not in teamManagersMap return null; // or a default value } const roster = yearManagers[rosterID]; if (!roster || !roster.team) { // Handle the case where rosterID is not found or team is undefined return null; // or a default value } return roster.team.avatar; }`

This does appear to fix the issue. I'm guessing its the future roundup where the participant hasn't yet been decided causing the issue. With this fix it displays as a gray circle with the text team avatar. It should probably just be blank when a team isn't found.
