### ISSUE TITLE
Import League History from Spreadsheet

### ISSUE THREAD

**Issue by sparker0285** [nmelhado/league-page#34]
**Is your feature request related to a problem? Please describe.**
Our league moved from ESPN to Sleeper last year.  Since Sleeper is newer than many other platforms, I suspect this may be the case for others.  

**Describe the solution you'd like**
I would like a way to import league history from our old league.  At least final records and total points.  I have this data in a spreadsheet.  It would be awesome to provide a spreadsheet template (likely CSV) that we could dump data into and then pull league history data from that CSV into a League history page or integrate it somehow.  Using a CSV template, you could keep it vanilla while incorporating historical data for a league.

**Describe alternatives you've considered**
I could link to a Google Sheets site or shared Excel file from the website to view historical data.  I could publish the data as a Power BI dataset and link to a Power BI report as well.

**League ID**
726301806027722752

**Additional context**
I attached an example CSV (I zipped the file so GitHub would accept the file type) file containing data from my league.  I love what you have done and gladly donated a few dollars this morning after I got the website up and running!  This is great stuff.
[R04History.zip](https://github.com/nmelhado/league-page/files/6964033/R04History.zip)

**Comment by nmelhado** [comment]
Sleeper is supposed to be adding an "import league history" feature any day now. If there's a way to leverage that, it would keep things simple. If, once the feature releases, there's no way to take advantage of it, I'll look into adding another way for the data to be imported. Hopefully they release it soon so we can get an idea of what we're working with

**Comment by sparker0285** [comment]
Awesome, thanks for the info!  You can close this one out in that case.  Thanks!

**Comment by Haglerd** [comment]
Did the release work for this? I would love this feature as well.

**Comment by sparker0285** [comment]
You can manually enter league history in Sleeper now, yes.  It is pretty
time consuming though, depending on how far back you want to go.  It does
not import anything, it just allows you to manually enter the data in the
web.
