### ISSUE TITLE
Direct link to manager from Roster page

### ISSUE THREAD

**Issue by fernmed** [nmelhado/league-page#35]
**Is your feature request related to a problem? Please describe.**
Clicking on Manager name on Roster page currently does not lead to that Manager's page.

**Describe the solution you'd like**
Not a big thing by any means, but would save a click to be able to click on Manager name or icon and go to their page directly. Would save a click. But just a small suggestion and nothing urgent at all. 

Thanks!

**Comment by nmelhado** [comment]
Agreed! That's the next change coming out. Should have it up by Friday.
