### ISSUE TITLE
[ENHANCEMENT] Make bio HTMLable

### ISSUE THREAD

**Issue by HansPeterOrding** [nmelhado/league-page#36]
**Describe the solution you'd like**
The Bio field should be rendered in a way so that HMTL is possible. This could easily be done by prefixing @html to the variable in src/lib/Managers/Manager.svelte

**League ID**
695913371186307072

**Additional context**
As this information is only managed by someone who is capable of at least editing code, it should be acceptable to not sanitize this field and just add @html.

**Comment by nmelhado** [comment]
Should have done this from the beginning. Fixed in https://github.com/nmelhado/league-page/pull/37

**Comment by HansPeterOrding** [comment]
It's a real pleasure working with you!
Just a minor update: Our pages have gone live just now. We are currently collecting all data from our managers. As soon as all data is collected and deployed to the pages, I will explicitly make an announcement to all our players (~300) that we would appreciate a donation to you!

**Comment by nmelhado** [comment]
Thank you! That's very kind.  Keep me posted on how the release goes and if there are any changes or features that people request
