### ISSUE TITLE
[ENHANCEMENT] Bench spots are not really readable in dark mode

### ISSUE THREAD

**Issue by HansPeterOrding** [nmelhado/league-page#43]
**Is your feature request related to a problem? Please describe.**
Since introduction of the dark layout, the bench spots are still background white and therefore nearly not readable.

**Describe the solution you'd like**
Either change the background color or the text color to enhance contrast and readability.

**Comment by nmelhado** [comment]
I noticed that too! It was fixed in or https://github.com/nmelhado/league-page/commit/66db1055d887a00b999f6ec14219276632114029

**Comment by nmelhado** [comment]
I also tweaked a few other css values for better visibility and added better accommodation for defensive players
