### ISSUE TITLE
[BUG]Auction draft results are incorrect

### ISSUE THREAD

**Issue by littlegiantsbanes** [nmelhado/league-page#45]
**Describe the bug**
Our league does auction format and the draft board does not correlate with the actual draft board.  The formatting and order is off.  Players on the wrong teams and teams with the wrong number of players

**718875521139699712**
In many cases, the bug maybe related to something not yet accommodated for in League Page, or something specific to your league. Adding your league ID allows for a faster debug and bug fix.

**To Reproduce**
Go to drafts, scroll to previous drafts, see draft board is mixed up.

**Expected behavior**
Expectation is for previous drafts to mirror sleeper draft board with players assigned to correct teams and dollar values displayed

**Screenshots**
what we see on the league page
<img width="964" alt="Screen Shot 2021-08-19 at 11 48 44 AM" src="https://user-images.githubusercontent.com/89208910/130100682-2d655651-a15c-4171-be47-b8d1e7771692.png">

what displays on the draft board aka ideal state
<img width="940" alt="Screen Shot 2021-08-19 at 11 49 26 AM" src="https://user-images.githubusercontent.com/89208910/130100683-fb95c1b6-047d-4703-97a5-9fc071467877.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur
 - Browser Safari
 - Version 14.1.1

**Additional context**
With auction being new, not sure if its an API issue with sleeper.

**Comment by nmelhado** [comment]
I hadn't been able to test auction leagues yet, so I've been curious about when the first bug would come up and how different it would be... looks pretty significant haha. I'll start diving into the API and working on a fix for auction leagues.

**Comment by nmelhado** [comment]
Fixed in https://github.com/nmelhado/league-page/pull/46
