### ISSUE TITLE
[BUG] Leaving manager info null fails for detail page

### ISSUE THREAD

**Issue by HansPeterOrding** [nmelhado/league-page#47]
**Describe the bug**
If you leave certain manger infos null, the displaying on the mangers detail page get's a little messy. The specific fields are:
* Location
* Fantasy since
* Preferred contact
* Favorite team
* Team philosophy
* Desire to trade

**Expected behavior**
The displaying of the properties should either be suppressed completely or a fallback placeholder should be displayed.

**Comment by nmelhado** [comment]
Fixed in https://github.com/nmelhado/league-page/pull/48
