### ISSUE TITLE
[BUG] CSS class REC_FLEX for roster spots missing

### ISSUE THREAD

**Issue by HansPeterOrding** [nmelhado/league-page#5]
**Describe the bug**
If your league contains a receiver flex position, in the League info -> Rosters screen the icon is not displayed. This is due to a not existing class "REC_FLEX".

**Your League ID**
721125042955554816

**To Reproduce**
1. Go to 'https://familyandfriends.upsidebowl.maysite.de/rosters'
2. See error

**Expected behavior**
The icon should be visible.

**Comment by nmelhado** [comment]
Fixed by https://github.com/nmelhado/league-page/pull/6
