### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mogaffar** [nmelhado/league-page#57]
**Describe the bug**

Matchup stats won’t pool idp projected points

**Your League ID**
In many cases, the bug maybe related to something not yet accommodated for in League Page, or something specific to your league. Adding your league ID allows for a faster debug and bug fix.

727925426831290368

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nmelhado** [comment]
Fixed in pr https://github.com/nmelhado/league-page/pull/58
