### ISSUE TITLE
[BUG] Sleeper info not loading

### ISSUE THREAD

**Issue by jgcar27** [nmelhado/league-page#60]
**Describe the bug**
Power rankings, matchups and transactions not loading from sleeper. Draft results show up.

**Your League ID**
735925090583183360

**To Reproduce**
https://ffpremierleague.vercel.app/
Looks like https://legends-league.vercel.app/ is doing the same.

**Expected behavior**

Happening on PC and Mobile

**Additional context**

**Comment by jgcar27** [comment]
made the changes, still having the same problem

**Comment by nmelhado** [comment]
Fixed in pr https://github.com/nmelhado/league-page/pull/62
