### ISSUE TITLE
Worst Weekly Performances [ENHANCEMENT]

### ISSUE THREAD

**Issue by Biomusician** [nmelhado/league-page#74]
Similar to how the page automatically pulls the top 10 weekly scorers, it would be neat to see who has scored the worst ever in the history of the league. Bottom-10 weekly/seasonal scorers would be fun to "recognize" the worst of the worst!

**Comment by nmelhado** [comment]
feature added by @OldNewsBlues in pr https://github.com/nmelhado/league-page/pull/93

**Comment by Biomusician** [comment]
Thank you so much! This is awesome.
