### ISSUE TITLE
[ENHANCEMENT] Add Playoffs to Records Tab + Option to Filter Records by Regular Season, Playoffs, or Both

### ISSUE THREAD

**Issue by OldNewsBlues** [nmelhado/league-page#80]
Currently the Records tab only tracks regular season fantasy stats.

It'd be nice to add fantasy playoffs stats to the Records tab, along with an option (on the actual page) to filter the tables/graphs for RS, PO, or both.

Regarding playoffs stats, I'd personally want this limited to only the games in the actual playoff bracket (i.e. excluding the "toilet bowl" games in the losers bracket).  For various reasons - most commonly, the managers in the losers bracket just not caring to set their line-ups - stats from those games wouldn't be proper to include for record-keeping purposes.  But I realize other leagues may not have such issues and therefore may prefer to have those games included.  For that reason, if they were to be included by default, it'd be nice to have a variable in the code we can adjust to exclude them.

League ID: 725417455366799360

Thanks for all the amazing work you've done on this!  Seriously, this is such a high-quality resource, and I'm enjoying sharpening my own coding knowledge by tinkering with my league-page's code.

**Comment by nmelhado** [comment]
This is a very good idea. I'm inclined to only include playoffs as well. This will be open for at least a month though, so if anyone wants loser bracket rankings as well leave a comment and I'll add a toggle in the code to include or exclude them.

**Comment by nmelhado** [comment]
P.S. I'm a huge fan of [Svelte](https://svelte.dev/) as a JavaScript framework. So hopefully you enjoy messing around with the code in this project! I use it for all my personal projects and I find it performs way better than react and is significantly easier to write than react or other frameworks.

**Comment by nmelhado** [comment]
This request was echoed in issue https://github.com/nmelhado/league-page/issues/88

**Comment by nmelhado** [comment]
This is great. I like a lot of the things you've implemented in your page. I've started meeting your PRs and will try to get this stuff implemented asap. Thanks for all the hard work!

Also, feel free to update your contribution info in the package.json if you want. I wasn't sure if I should use your 2 account that created the PRs or your primary one instead.
