### ISSUE TITLE
[BUG] Playoffs Not Included in Biggest Blowouts/Narrowest Wins

### ISSUE THREAD

**Issue by Biomusician** [nmelhado/league-page#88]
**Describe the bug**
The biggest wins and narrowest blowouts in the league records page does not consider playoffs, only regular season. In our league's case, the narrowest victory was the 2019 championship, with a margin of 0.04 points.

**Your League ID**
675013542918848512

**Expected behavior**
The narrowest wins and biggest blowouts should include playoff and championship matches, if possible.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 94.0.4606.71 (Official Build) (64-bit)

**Comment by nmelhado** [comment]
This was requested in feature request https://github.com/nmelhado/league-page/issues/80. Follow along there for progress
