### ISSUE TITLE
[ENHANCEMENT] Previous Season Records and other stats from previous

### ISSUE THREAD

**Issue by camtmiller** [nmelhado/league-page#94]
We recently switched to sleeper for fantasy. Is there a way to add previous season records and all of the other stats. I currently have an excel with all of my data and would like to add it to my site.

**Comment by nmelhado** [comment]
This is being tracked in feature request https://github.com/nmelhado/league-page/issues/66. I'm going to close this so we can keep everything in one place. The goal is to implement this before the start of the '22 season
