### ISSUE TITLE
[BUG] Managers Issue with Divisions

### ISSUE THREAD

**Issue by Haglerd** [nmelhado/league-page#95]
**Describe the bug**
**To Reproduce**
I think there may be some issues with leagues that use divisions. I'm seeing some strange behavior and not sure what is going on. I've only updated the managers page to be unique and added a few pictures. I've reverted back to the basic managers code and didn't update anything but adding 12 managers from 3 and still had the same issues.  I think they are all related to my league being broken out to divisions. Which is causing the trophies page not to load. In turn scrambling the data. 

My trophies page is not properly loading. So, if I go to the trophy page, it will start loading and never finish. From there, any page you go to is inaccurate. It will show the names of managers that aren't right or standings or matchups for the wrong managers. However, one refresh of the page and that fixes it.  Any page you go to after the trophy page stalling. Will have a mix-up of the data. I showed two screenshots with description in title. I go to the before picture from the trophy page while it is loading. The data is wrong. I refresh, then the data is right. 

If you go to the standings page after the trophy page is messed up and don't refresh before going to another page, the corresponding page will also be messed up. If you refresh the page to fix the data, then any page after that will be back on track until you go to the trophy page again. The trophy page loaded once for me, but that was it. Not sure why it isn't loading now. I haven't messed with any code outside of managers and pictures pages. 

**Your League ID**
726145213692776448

**Expected behavior**
I would expect the manager(12) team to show the right picture. 
I would expect all links to work the first time you click them versus needing a second screen refresh to pull accurately.
I would expect the standings to reflect the right team and right record. 
I would expect the trophy page to load like the demo site. 

**Desktop (please complete the following information):**
 - OS: windows 10 
 - Browser chrome or safari
 - Version [e.g. 22] latest on both

**Smartphone (please complete the following information):**
 - Device: iphone 13 - OS: latest 
 - Browser safari
 - Version latest

**Additional context**
I wasn't sure the best way to submit this issue and to explain it. So please feel free to look at my site directly. You can then see that the first time it loads versus when you refresh whatever page you are on is different. 

https://league-page-woad-eta.vercel.app
![open managers from trophy page](https://user-images.githubusercontent.com/13811563/143092085-e1884bc8-0ed9-46f1-9118-cded903dc0c2.PNG)
![refresh managers page from managers page](https://user-images.githubusercontent.com/13811563/143092088-643d4388-23e5-4a81-b6cb-affa5b833769.PNG)
/

**Comment by Haglerd** [comment]
Still been playing around with this trying to figure out what is going on. For reference. I created a whole new site. If I just put in league id. I get the same issue. Trophys(awards) never loads.

**Comment by nmelhado** [comment]
Sorry for the delay, looking into this shortly. Should be something minor

**Comment by nmelhado** [comment]
I fixed the trophy page bug in pr https://github.com/nmelhado/league-page/pull/102. I wasn't able to reproduce the managers bug locally though. Could you try updating and letting me know if you are still experiencing it?
