### ISSUE TITLE
[BUG] - Championship / Consolation overview does not consider 2 Weeks Playoff setting

### ISSUE THREAD

**Issue by Justatix** [nmelhado/league-page#97]
**Describe the bug**
The Playoffs / Consolation Overview on the League Page is not considering the Playoffs setting of 2 Weeks. it only shows the 1 week result of it.

**Your League ID**
692769447512989696

**Expected behavior**
The aggregated sum of 2 games should be displayed in the playoff/consolation bracket

**Screenshots**
<img width="754" alt="Bildschirmfoto 2021-12-20 um 12 13 28" src="https://user-images.githubusercontent.com/95846607/146758707-4d616049-5fb8-4e9c-a69e-7200f4826e63.png">
<img width="868" alt="Bildschirmfoto 2021-12-20 um 12 13 42" src="https://user-images.githubusercontent.com/95846607/146758716-10a83eb1-3561-4cee-8c23-72bd800f204b.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.1
 - Browser Safari
 - Version 15.2

**Additional context**

**Comment by nmelhado** [comment]
Going to try to tackle this, but will have to be fixed for next season at this point. Sorry I wasn't able to get to this for this season.

**Comment by Justatix** [comment]
no worries, there's no urgency in that. glad you'd take this up, thanks for your effort!

**Comment by nmelhado** [comment]
Fixed in https://github.com/nmelhado/league-page/pull/113! Should be good to go for next season
